In [1]:
#importing various libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import os
os.getcwd()

'C:\\Users\\Vivek'

In [3]:
os.chdir('C:\\Users\\Vivek\Desktop')

In [4]:
#Reading the data
fraud_train = pd.read_csv('fraudTrain.csv')

In [5]:
fraud_train

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,01-01-2019 00:00,2.703190e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",09-03-1988,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,01-01-2019 00:00,6.304230e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,21-06-1978,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,01-01-2019 00:00,3.885950e+13,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,19-01-1962,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,01-01-2019 00:01,3.534090e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,12-01-1967,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,01-01-2019 00:03,3.755340e+14,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,28-03-1986,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,1048570,10-03-2020 16:07,6.011980e+15,fraud_Fadel Inc,health_fitness,77.00,Haley,Wagner,F,05561 Farrell Crescent,...,39.0305,-76.5515,92106,"Accountant, chartered certified",28-05-1943,45ecd198c65e81e597db22e8d2ef7361,1362931649,38.779464,-76.317042,0
1048571,1048571,10-03-2020 16:07,4.839040e+15,"fraud_Cremin, Hamill and Reichel",misc_pos,116.94,Meredith,Campbell,F,043 Hanson Turnpike,...,41.1826,-92.3097,1583,Geochemist,28-06-1999,c00ce51c6ebb7657474a77b9e0b51f34,1362931670,41.400318,-92.726724,0
1048572,1048572,10-03-2020 16:08,5.718440e+11,"fraud_O'Connell, Botsford and Hand",home,21.27,Susan,Mills,F,005 Cody Estates,...,38.2507,-85.7476,736284,Engineering geologist,02-04-1952,17c9dc8b2a6449ca2473726346e58e6c,1362931711,37.293339,-84.798122,0
1048573,1048573,10-03-2020 16:08,4.646850e+18,fraud_Thompson-Gleason,health_fitness,9.52,Julia,Bell,F,576 House Crossroad,...,40.7320,-73.1000,4056,Film/video editor,25-06-1990,5ca650881b48a6a38754f841c23b77ab,1362931718,39.773077,-72.213209,0
1048574,1048574,10-03-2020 16:08,2.283740e+15,fraud_Buckridge PLC,misc_pos,6.81,Shannon,Williams,F,9345 Spencer Junctions Suite 183,...,34.0770,-84.3033,165556,Prison officer,27-12-1997,8d0a575fe635bbde12f1a2bffc126731,1362931730,33.601468,-83.891921,0

In [6]:
fraud_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1048575 non-null  int64
 1   trans_date_trans_time  1048575 non-null  object
 2   cc_num                 1048575 non-null  float64
 3   merchant               1048575 non-null  object
 4   category               1048575 non-null  object
 5   amt                    1048575 non-null  float64
 6   first                  1048575 non-null  object
 7   last                   1048575 non-null  object
 8   gender                 1048575 non-null  object
 9   street                 1048575 non-null  object
 10  city                   1048575 non-null  object
 11  state                  1048575 non-null  object
 12  zip                    1048575 non-null  int64
 13  lat                    1048575 non-null  float64
 14  long                   1048575 non-null  float64
 15  city_pop               1048575 non-null  int64
 16  job                    1048575 non-null  object
 17  dob                    1048575 non-null  object
 18  trans_num              1048575 non-null  object
 19  unix_time              1048575 non-null  int64
 20  merch_lat              1048575 non-null  float64
 21  merch_long             1048575 non-null  float64
 22  is_fraud               1048575 non-null  int64
dtypes: float64(6), int64(5), object(12)
memory usage: 184.0+ MB

In [7]:
fraud_train.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,01-01-2019 00:00,2.703190e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",09-03-1988,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,01-01-2019 00:00,6.304230e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,21-06-1978,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,01-01-2019 00:00,3.885950e+13,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,19-01-1962,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,01-01-2019 00:01,3.534090e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,12-01-1967,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,01-01-2019 00:03,3.755340e+14,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,28-03-1986,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [8]:
from sklearn import preprocessing

In [9]:
fraud_train.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [10]:
fraud_train.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [11]:
fraud_train.drop(columns=['Unnamed: 0','trans_num','street'],axis=1,inplace=True)

In [12]:
fraud_train

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,city,state,zip,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud
0,01-01-2019 00:00,2.703190e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",09-03-1988,1325376018,36.011293,-82.048315,0
1,01-01-2019 00:00,6.304230e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,21-06-1978,1325376044,49.159047,-118.186462,0
2,01-01-2019 00:00,3.885950e+13,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,19-01-1962,1325376051,43.150704,-112.154481,0
3,01-01-2019 00:01,3.534090e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,Boulder,MT,59632,46.2306,-112.1138,1939,Patent attorney,12-01-1967,1325376076,47.034331,-112.561071,0
4,01-01-2019 00:03,3.755340e+14,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,Doe Hill,VA,24433,38.4207,-79.4629,99,Dance movement psychotherapist,28-03-1986,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,10-03-2020 16:07,6.011980e+15,fraud_Fadel Inc,health_fitness,77.00,Haley,Wagner,F,Annapolis,MD,21405,39.0305,-76.5515,92106,"Accountant, chartered certified",28-05-1943,1362931649,38.779464,-76.317042,0
1048571,10-03-2020 16:07,4.839040e+15,"fraud_Cremin, Hamill and Reichel",misc_pos,116.94,Meredith,Campbell,F,Hedrick,IA,52563,41.1826,-92.3097,1583,Geochemist,28-06-1999,1362931670,41.400318,-92.726724,0
1048572,10-03-2020 16:08,5.718440e+11,"fraud_O'Connell, Botsford and Hand",home,21.27,Susan,Mills,F,Louisville,KY,40202,38.2507,-85.7476,736284,Engineering geologist,02-04-1952,1362931711,37.293339,-84.798122,0
1048573,10-03-2020 16:08,4.646850e+18,fraud_Thompson-Gleason,health_fitness,9.52,Julia,Bell,F,West Sayville,NY,11796,40.7320,-73.1000,4056,Film/video editor,25-06-1990,1362931718,39.773077,-72.213209,0
1048574,10-03-2020 16:08,2.283740e+15,fraud_Buckridge PLC,misc_pos,6.81,Shannon,Williams,F,Alpharetta,GA,30009,34.0770,-84.3033,165556,Prison officer,27-12-1997,1362931730,33.601468,-83.891921,0

In [13]:
#Since the data is too long we take 10000 entries only as memory should not exceed
df= fraud_train.head(n=10000)
df.is_fraud.value_counts()

In [14]:
df.shape

(10000, 20)

In [15]:
df

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,city,state,zip,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud
0,01-01-2019 00:00,2.703190e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",09-03-1988,1325376018,36.011293,-82.048315,0
1,01-01-2019 00:00,6.304230e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,21-06-1978,1325376044,49.159047,-118.186462,0
2,01-01-2019 00:00,3.885950e+13,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,19-01-1962,1325376051,43.150704,-112.154481,0
3,01-01-2019 00:01,3.534090e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,Boulder,MT,59632,46.2306,-112.1138,1939,Patent attorney,12-01-1967,1325376076,47.034331,-112.561071,0
4,01-01-2019 00:03,3.755340e+14,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,Doe Hill,VA,24433,38.4207,-79.4629,99,Dance movement psychotherapist,28-03-1986,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,07-01-2019 03:49,6.011400e+15,"fraud_Stokes, Christiansen and Sipes",grocery_net,93.06,Maria,Roy,F,Sheffield,MA,1257,42.1001,-73.3611,2121,Radio producer,14-10-1973,1325908195,41.603464,-73.171564,0
9996,07-01-2019 03:52,4.467460e+18,"fraud_Heller, Gutmann and Zieme",grocery_pos,63.62,Rita,Myers,F,Tampa,FL,33620,28.0600,-82.4079,717255,Waste management officer,16-09-1966,1325908354,27.088400,-83.180925,0
9997,07-01-2019 03:53,4.689150e+18,fraud_Dooley Inc,shopping_pos,5.71,Steven,Brooks,M,Manley,NE,68403,40.9207,-96.1680,206,Human resources officer,04-10-1967,1325908392,40.633368,-96.595273,0
9998,07-01-2019 03:53,3.739050e+14,fraud_Schamberger-O'Keefe,grocery_pos,231.45,Sarah,Bishop,F,Meridian,TX,76665,31.9290,-97.6443,2526,Phytotherapist,12-11-1970,1325908431,32.807117,-98.639187,0
9999,07-01-2019 03:53,3.556610e+15,fraud_Strosin-Cruickshank,grocery_pos,49.49,Jose,Vasquez,M,Lake Jackson,TX,77566,29.0393,-95.4401,28739,Futures trader,27-12-1999,1325908434,29.378479,-95.406067,0

In [16]:
#Cnverting categorical variables into indicator variables
final = pd.get_dummies(data = df)

In [17]:
final

,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud,...,dob_31-05-1948,dob_31-05-1994,dob_31-05-1999,dob_31-07-1941,dob_31-07-1961,dob_31-07-1975,dob_31-08-1984,dob_31-08-1985,dob_31-12-1972,dob_31-12-1986
0,2.703190e+15,4.97,28654,36.0788,-81.1781,3495,1325376018,36.011293,-82.048315,0,...,0,0,0,0,0,0,0,0,0,0
1,6.304230e+11,107.23,99160,48.8878,-118.2105,149,1325376044,49.159047,-118.186462,0,...,0,0,0,0,0,0,0,0,0,0
2,3.885950e+13,220.11,83252,42.1808,-112.2620,4154,1325376051,43.150704,-112.154481,0,...,0,0,0,0,0,0,0,0,0,0
3,3.534090e+15,45.00,59632,46.2306,-112.1138,1939,1325376076,47.034331,-112.561071,0,...,0,0,0,0,0,0,0,0,0,0
4,3.755340e+14,41.96,24433,38.4207,-79.4629,99,1325376186,38.674999,-78.632459,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,6.011400e+15,93.06,1257,42.1001,-73.3611,2121,1325908195,41.603464,-73.171564,0,...,0,0,0,0,0,0,0,0,0,0
9996,4.467460e+18,63.62,33620,28.0600,-82.4079,717255,1325908354,27.088400,-83.180925,0,...,0,0,0,0,0,0,0,0,0,0
9997,4.689150e+18,5.71,68403,40.9207,-96.1680,206,1325908392,40.633368,-96.595273,0,...,0,0,0,0,0,0,0,0,0,0
9998,3.739050e+14,231.45,76665,31.9290,-97.6443,2526,1325908431,32.807117,-98.639187,0,...,0,0,0,0,0,0,0,0,0,0
9999,3.556610e+15,49.49,77566,29.0393,-95.4401,28739,1325908434,29.378479,-95.406067,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
x_train = final.drop(columns='is_fraud',axis=1)
y_train = final['is_fraud']

*For Test Data*

In [19]:
fraud_test= pd.read_csv('fraudTest.csv')

In [20]:
fraud_test

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,21-06-2020 12:14,2.291160e+15,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,19-03-1968,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,21-06-2020 12:14,3.573030e+15,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",17-01-1990,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,21-06-2020 12:14,3.598220e+15,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",21-10-1970,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,21-06-2020 12:15,3.591920e+15,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,25-07-1987,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,21-06-2020 12:15,3.526830e+15,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,06-07-1955,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,31-12-2020 23:59,3.056060e+13,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,40.4931,-91.8912,519,Town planner,13-02-1966,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
555715,555715,31-12-2020 23:59,3.556610e+15,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,29.0393,-95.4401,28739,Futures trader,27-12-1999,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
555716,555716,31-12-2020 23:59,6.011720e+15,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,46.1966,-118.9017,3684,Musician,29-11-1981,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
555717,555717,31-12-2020 23:59,4.079770e+12,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,...,44.6255,-116.4493,129,Cartographer,15-12-1965,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
555718,555718,31-12-2020 23:59,4.170690e+15,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,...,35.6665,-97.4798,116001,Media buyer,10-05-1993,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [21]:
fraud_test.drop(columns=['Unnamed: 0','trans_num','street'],axis=1,inplace=True)

In [22]:
fraud_test

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,city,state,zip,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud
0,21-06-2020 12:14,2.291160e+15,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,Columbia,SC,29209,33.9659,-80.9355,333497,Mechanical engineer,19-03-1968,1371816865,33.986391,-81.200714,0
1,21-06-2020 12:14,3.573030e+15,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,Altonah,UT,84002,40.3207,-110.4360,302,"Sales professional, IT",17-01-1990,1371816873,39.450498,-109.960431,0
2,21-06-2020 12:14,3.598220e+15,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,Bellmore,NY,11710,40.6729,-73.5365,34496,"Librarian, public",21-10-1970,1371816893,40.495810,-74.196111,0
3,21-06-2020 12:15,3.591920e+15,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,Titusville,FL,32780,28.5697,-80.8191,54767,Set designer,25-07-1987,1371816915,28.812398,-80.883061,0
4,21-06-2020 12:15,3.526830e+15,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,Falmouth,MI,49632,44.2529,-85.0170,1126,Furniture designer,06-07-1955,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,31-12-2020 23:59,3.056060e+13,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,Luray,MO,63453,40.4931,-91.8912,519,Town planner,13-02-1966,1388534347,39.946837,-91.333331,0
555715,31-12-2020 23:59,3.556610e+15,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,Lake Jackson,TX,77566,29.0393,-95.4401,28739,Futures trader,27-12-1999,1388534349,29.661049,-96.186633,0
555716,31-12-2020 23:59,6.011720e+15,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,Burbank,WA,99323,46.1966,-118.9017,3684,Musician,29-11-1981,1388534355,46.658340,-119.715054,0
555717,31-12-2020 23:59,4.079770e+12,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,Mesa,ID,83643,44.6255,-116.4493,129,Cartographer,15-12-1965,1388534364,44.470525,-117.080888,0
555718,31-12-2020 23:59,4.170690e+15,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,Edmond,OK,73034,35.6665,-97.4798,116001,Media buyer,10-05-1993,1388534374,36.210097,-97.036372,0

In [23]:
test_data= fraud_test.sample(frac=1,random_state=1).reset_index()
test_data = fraud_test.head(n= 14590)

In [24]:
final_test= pd.get_dummies(data = test_data)

In [25]:
final_test

,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud,...,dob_31-05-1948,dob_31-05-1994,dob_31-05-1999,dob_31-07-1941,dob_31-07-1961,dob_31-07-1975,dob_31-08-1984,dob_31-08-1985,dob_31-12-1972,dob_31-12-1986
0,2.291160e+15,2.86,29209,33.9659,-80.9355,333497,1371816865,33.986391,-81.200714,0,...,0,0,0,0,0,0,0,0,0,0
1,3.573030e+15,29.84,84002,40.3207,-110.4360,302,1371816873,39.450498,-109.960431,0,...,0,0,0,0,0,0,0,0,0,0
2,3.598220e+15,41.28,11710,40.6729,-73.5365,34496,1371816893,40.495810,-74.196111,0,...,0,0,0,0,0,0,0,0,0,0
3,3.591920e+15,60.05,32780,28.5697,-80.8191,54767,1371816915,28.812398,-80.883061,0,...,0,0,0,0,0,0,0,0,0,0
4,3.526830e+15,3.19,49632,44.2529,-85.0170,1126,1371816917,44.959148,-85.884734,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14585,3.523900e+15,90.50,10463,40.8798,-73.9067,1382480,1372234525,41.223511,-73.816515,0,...,0,0,0,0,0,0,0,0,0,0
14586,3.013520e+13,241.58,64058,39.1412,-94.3515,123373,1372234557,39.143520,-95.164599,0,...,0,0,0,0,0,0,0,0,0,0
14587,3.517810e+15,71.21,24983,37.5802,-80.5248,2443,1372234598,36.975386,-81.458947,0,...,0,0,0,0,0,0,0,0,0,0
14588,4.890420e+18,73.86,95827,38.5662,-121.3286,757530,1372234629,38.693488,-120.953350,0,...,0,0,0,0,0,0,0,0,0,0
14589,4.501450e+15,61.69,57439,45.3290,-98.0837,52,1372234684,45.915255,-98.648984,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
x_test=final_test.drop('is_fraud',axis=1)
y_test=final_test['is_fraud']

**MODELING**

In [27]:
from sklearn.model_selection import train_test_split

**Logistic Regression**

In [28]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear')
model.fit(x_train,y_train)

LogisticRegression(solver='liblinear')

In [29]:
Predictions = model.predict(x_test)

C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- city_New Franken
- city_Pea Ridge
- city_Spirit Lake
- city_Springville
- city_West Bethel
- ...
Feature names seen at fit time, yet now missing:
- dob_28-10-1960
- trans_date_trans_time_01-01-2019 00:00
- trans_date_trans_time_01-01-2019 00:01
- trans_date_trans_time_01-01-2019 00:03
- trans_date_trans_time_01-01-2019 00:04
- ...

  warnings.warn(message, FutureWarning)

In [30]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,f1_score

In [31]:
model_accuracy = accuracy_score(y_test,Predictions)

In [32]:
model_accuracy

0.9969156956819739

**Decision Tree**

In [33]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(x_train,y_train)

DecisionTreeClassifier()

In [34]:
predictions= dtree.predict(x_test)

C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- city_New Franken
- city_Pea Ridge
- city_Spirit Lake
- city_Springville
- city_West Bethel
- ...
Feature names seen at fit time, yet now missing:
- dob_28-10-1960
- trans_date_trans_time_01-01-2019 00:00
- trans_date_trans_time_01-01-2019 00:01
- trans_date_trans_time_01-01-2019 00:03
- trans_date_trans_time_01-01-2019 00:04
- ...

  warnings.warn(message, FutureWarning)

In [35]:
Tree_accuracy = accuracy_score(y_test,Predictions)

In [36]:
Tree_accuracy

0.9969156956819739

In [37]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14545
           1       0.16      0.16      0.16        45

    accuracy                           0.99     14590
   macro avg       0.58      0.58      0.58     14590
weighted avg       0.99      0.99      0.99     14590

**Random Forest**

In [38]:
from sklearn.ensemble import RandomForestClassifier

In [39]:
rfc = RandomForestClassifier(n_estimators=200)

In [40]:
rfc.fit(x_train,y_train)

RandomForestClassifier(n_estimators=200)

In [41]:
RF_predictions = rfc.predict(x_test)

C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- city_New Franken
- city_Pea Ridge
- city_Spirit Lake
- city_Springville
- city_West Bethel
- ...
Feature names seen at fit time, yet now missing:
- dob_28-10-1960
- trans_date_trans_time_01-01-2019 00:00
- trans_date_trans_time_01-01-2019 00:01
- trans_date_trans_time_01-01-2019 00:03
- trans_date_trans_time_01-01-2019 00:04
- ...

  warnings.warn(message, FutureWarning)

In [42]:
RF_accuracy = accuracy_score(y_test,RF_predictions)

In [43]:
RF_accuracy

0.9969156956819739

In [44]:
print("Classification Report:\n", classification_report(y_test,RF_predictions))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     14545
           1       0.00      0.00      0.00        45

    accuracy                           1.00     14590
   macro avg       0.50      0.50      0.50     14590
weighted avg       0.99      1.00      1.00     14590

C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

**KNN**

In [45]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [46]:
 knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [47]:
knn_predictions = knn.predict(x_test)

C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- city_New Franken
- city_Pea Ridge
- city_Spirit Lake
- city_Springville
- city_West Bethel
- ...
Feature names seen at fit time, yet now missing:
- dob_28-10-1960
- trans_date_trans_time_01-01-2019 00:00
- trans_date_trans_time_01-01-2019 00:01
- trans_date_trans_time_01-01-2019 00:03
- trans_date_trans_time_01-01-2019 00:04
- ...

  warnings.warn(message, FutureWarning)
C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [48]:
print("Accuracy:\n", accuracy_score(y_test,knn_predictions))

Accuracy:
 0.9952021932830706

In [49]:
print("Classification Report:\n", classification_report(y_test,knn_predictions))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     14545
           1       0.00      0.00      0.00        45

    accuracy                           1.00     14590
   macro avg       0.50      0.50      0.50     14590
weighted avg       0.99      1.00      0.99     14590

In [50]:
from sklearn.svm import SVC

In [51]:
from sklearn.model_selection import GridSearchCV

In [52]:
param_grid = {'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.01,0.001,0.0001]}

In [53]:
grid = GridSearchCV(SVC(),param_grid,verbose=3,refit=True)

In [54]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ....................C=0.1, gamma=1;, score=0.996 total time= 1.7min
[CV 2/5] END ....................C=0.1, gamma=1;, score=0.996 total time= 1.7min
[CV 3/5] END ....................C=0.1, gamma=1;, score=0.996 total time= 1.6min
[CV 4/5] END ....................C=0.1, gamma=1;, score=0.995 total time= 1.7min
[CV 5/5] END ....................C=0.1, gamma=1;, score=0.995 total time= 1.7min
[CV 1/5] END ..................C=0.1, gamma=0.1;, score=0.996 total time= 1.7min
[CV 2/5] END ..................C=0.1, gamma=0.1;, score=0.996 total time= 1.8min
[CV 3/5] END ..................C=0.1, gamma=0.1;, score=0.996 total time= 1.6min
[CV 4/5] END ..................C=0.1, gamma=0.1;, score=0.995 total time= 1.7min
[CV 5/5] END ..................C=0.1, gamma=0.1;, score=0.995 total time= 1.7min
[CV 1/5] END .................C=0.1, gamma=0.01;, score=0.996 total time= 1.7min
[CV 2/5] END .................C=0.1, gamma=0.01;, score=0.996 total time= 1.7min
[CV 3/5] END .................C=0.1, gamma=0.01;, score=0.996 total time= 1.6min
[CV 4/5] END .................C=0.1, gamma=0.01;, score=0.995 total time= 1.7min
[CV 5/5] END .................C=0.1, gamma=0.01;, score=0.995 total time= 1.7min
[CV 1/5] END ................C=0.1, gamma=0.001;, score=0.996 total time= 1.7min
[CV 2/5] END ................C=0.1, gamma=0.001;, score=0.996 total time= 1.7min
[CV 3/5] END ................C=0.1, gamma=0.001;, score=0.996 total time= 1.6min
[CV 4/5] END ................C=0.1, gamma=0.001;, score=0.995 total time= 1.7min
[CV 5/5] END ................C=0.1, gamma=0.001;, score=0.995 total time= 1.8min
[CV 1/5] END ...............C=0.1, gamma=0.0001;, score=0.996 total time= 1.7min
[CV 2/5] END ...............C=0.1, gamma=0.0001;, score=0.996 total time= 1.7min
[CV 3/5] END ...............C=0.1, gamma=0.0001;, score=0.996 total time= 1.6min
[CV 4/5] END ...............C=0.1, gamma=0.0001;, score=0.995 total time= 1.7min
[CV 5/5] END ...............C=0.1, gamma=0.0001;, score=0.995 total time= 1.7min
[CV 1/5] END ......................C=1, gamma=1;, score=0.996 total time= 2.2min
[CV 2/5] END ......................C=1, gamma=1;, score=0.996 total time= 1.9min
[CV 3/5] END ......................C=1, gamma=1;, score=0.996 total time= 2.2min
[CV 4/5] END ......................C=1, gamma=1;, score=0.995 total time= 2.4min
[CV 5/5] END ......................C=1, gamma=1;, score=0.995 total time= 2.4min
[CV 1/5] END ....................C=1, gamma=0.1;, score=0.996 total time= 2.3min
[CV 2/5] END ....................C=1, gamma=0.1;, score=0.996 total time= 2.0min
[CV 3/5] END ....................C=1, gamma=0.1;, score=0.996 total time= 2.3min
[CV 4/5] END ....................C=1, gamma=0.1;, score=0.995 total time= 2.5min
[CV 5/5] END ....................C=1, gamma=0.1;, score=0.995 total time= 2.2min
[CV 1/5] END ...................C=1, gamma=0.01;, score=0.996 total time= 2.3min
[CV 2/5] END ...................C=1, gamma=0.01;, score=0.996 total time= 1.9min
[CV 3/5] END ...................C=1, gamma=0.01;, score=0.996 total time= 2.3min
[CV 4/5] END ...................C=1, gamma=0.01;, score=0.995 total time= 2.4min
[CV 5/5] END ...................C=1, gamma=0.01;, score=0.995 total time= 2.2min
[CV 1/5] END ..................C=1, gamma=0.001;, score=0.996 total time= 2.3min
[CV 2/5] END ..................C=1, gamma=0.001;, score=0.996 total time= 1.9min
[CV 3/5] END ..................C=1, gamma=0.001;, score=0.996 total time= 2.3min
[CV 4/5] END ..................C=1, gamma=0.001;, score=0.995 total time= 2.3min
[CV 5/5] END ..................C=1, gamma=0.001;, score=0.995 total time= 2.2min
[CV 1/5] END .................C=1, gamma=0.0001;, score=0.996 total time= 2.3min
[CV 2/5] END .................C=1, gamma=0.0001;, score=0.996 total time= 2.0min
[CV 3/5] END .................C=1, gamma=0.0001;, score=0.996 total time= 2.3min
[CV 4/5] END .................C=1, gamma=0.0001;, score=0.995 total time= 2.4min
[CV 5/5] END .................C=1, gamma=0.0001;, score=0.995 total time= 2.2min
[CV 1/5] END .....................C=10, gamma=1;, score=0.996 total time= 1.8min
[CV 2/5] END .....................C=10, gamma=1;, score=0.996 total time= 1.9min
[CV 3/5] END .....................C=10, gamma=1;, score=0.996 total time= 3.0min
[CV 4/5] END .....................C=10, gamma=1;, score=0.995 total time= 1.7min
[CV 5/5] END .....................C=10, gamma=1;, score=0.995 total time= 1.7min
[CV 1/5] END ...................C=10, gamma=0.1;, score=0.996 total time= 1.8min
[CV 2/5] END ...................C=10, gamma=0.1;, score=0.996 total time= 1.9min
[CV 3/5] END ...................C=10, gamma=0.1;, score=0.996 total time= 2.9min
[CV 4/5] END ...................C=10, gamma=0.1;, score=0.995 total time= 1.7min
[CV 5/5] END ...................C=10, gamma=0.1;, score=0.995 total time= 1.7min
[CV 1/5] END ..................C=10, gamma=0.01;, score=0.996 total time= 1.9min
[CV 2/5] END ..................C=10, gamma=0.01;, score=0.996 total time= 2.0min
[CV 3/5] END ..................C=10, gamma=0.01;, score=0.996 total time= 3.0min
[CV 4/5] END ..................C=10, gamma=0.01;, score=0.995 total time= 1.7min
[CV 5/5] END ..................C=10, gamma=0.01;, score=0.995 total time= 1.7min
[CV 1/5] END .................C=10, gamma=0.001;, score=0.996 total time= 1.8min
[CV 2/5] END .................C=10, gamma=0.001;, score=0.996 total time= 2.2min
[CV 3/5] END .................C=10, gamma=0.001;, score=0.996 total time= 3.2min
[CV 4/5] END .................C=10, gamma=0.001;, score=0.995 total time= 1.8min
[CV 5/5] END .................C=10, gamma=0.001;, score=0.995 total time= 1.8min
[CV 1/5] END ................C=10, gamma=0.0001;, score=0.996 total time= 1.7min
[CV 2/5] END ................C=10, gamma=0.0001;, score=0.996 total time= 2.1min
[CV 3/5] END ................C=10, gamma=0.0001;, score=0.996 total time= 3.4min
[CV 4/5] END ................C=10, gamma=0.0001;, score=0.995 total time= 1.9min
[CV 5/5] END ................C=10, gamma=0.0001;, score=0.995 total time= 2.0min
[CV 1/5] END ....................C=100, gamma=1;, score=0.996 total time= 2.0min
[CV 2/5] END ....................C=100, gamma=1;, score=0.996 total time= 2.2min
[CV 3/5] END ....................C=100, gamma=1;, score=0.996 total time= 3.7min
[CV 4/5] END ....................C=100, gamma=1;, score=0.995 total time= 2.3min
[CV 5/5] END ....................C=100, gamma=1;, score=0.995 total time= 2.2min
[CV 1/5] END ..................C=100, gamma=0.1;, score=0.996 total time= 2.1min
[CV 2/5] END ..................C=100, gamma=0.1;, score=0.996 total time= 2.1min
[CV 3/5] END ..................C=100, gamma=0.1;, score=0.996 total time= 3.8min
[CV 4/5] END ..................C=100, gamma=0.1;, score=0.995 total time= 2.3min
[CV 5/5] END ..................C=100, gamma=0.1;, score=0.995 total time= 2.1min
[CV 1/5] END .................C=100, gamma=0.01;, score=0.996 total time= 2.1min
[CV 2/5] END .................C=100, gamma=0.01;, score=0.996 total time= 2.1min
[CV 3/5] END .................C=100, gamma=0.01;, score=0.996 total time= 3.4min
[CV 4/5] END .................C=100, gamma=0.01;, score=0.995 total time= 1.9min
[CV 5/5] END .................C=100, gamma=0.01;, score=0.995 total time= 1.8min
[CV 1/5] END ................C=100, gamma=0.001;, score=0.996 total time= 1.7min
[CV 2/5] END ................C=100, gamma=0.001;, score=0.996 total time= 1.8min
[CV 3/5] END ................C=100, gamma=0.001;, score=0.996 total time= 3.1min
[CV 4/5] END ................C=100, gamma=0.001;, score=0.995 total time= 1.9min
[CV 5/5] END ................C=100, gamma=0.001;, score=0.995 total time= 1.8min
[CV 1/5] END ...............C=100, gamma=0.0001;, score=0.996 total time= 1.9min
[CV 2/5] END ...............C=100, gamma=0.0001;, score=0.996 total time= 2.0min
[CV 3/5] END ...............C=100, gamma=0.0001;, score=0.996 total time= 3.5min
[CV 4/5] END ...............C=100, gamma=0.0001;, score=0.995 total time= 2.0min
[CV 5/5] END ...............C=100, gamma=0.0001;, score=0.995 total time= 2.1min
[CV 1/5] END ...................C=1000, gamma=1;, score=0.004 total time= 2.4min
[CV 2/5] END ...................C=1000, gamma=1;, score=0.004 total time= 2.4min
[CV 3/5] END ...................C=1000, gamma=1;, score=0.004 total time= 3.1min
[CV 4/5] END ...................C=1000, gamma=1;, score=0.005 total time= 1.9min
[CV 5/5] END ...................C=1000, gamma=1;, score=0.005 total time= 1.8min
[CV 1/5] END .................C=1000, gamma=0.1;, score=0.004 total time= 1.9min
[CV 2/5] END .................C=1000, gamma=0.1;, score=0.004 total time= 1.9min
[CV 3/5] END .................C=1000, gamma=0.1;, score=0.004 total time= 2.9min
[CV 4/5] END .................C=1000, gamma=0.1;, score=0.005 total time= 1.9min
[CV 5/5] END .................C=1000, gamma=0.1;, score=0.005 total time= 1.8min
[CV 1/5] END ................C=1000, gamma=0.01;, score=0.004 total time= 1.9min
[CV 2/5] END ................C=1000, gamma=0.01;, score=0.004 total time= 1.9min
[CV 3/5] END ................C=1000, gamma=0.01;, score=0.004 total time= 2.9min
[CV 4/5] END ................C=1000, gamma=0.01;, score=0.005 total time= 1.9min
[CV 5/5] END ................C=1000, gamma=0.01;, score=0.005 total time= 1.9min
[CV 1/5] END ...............C=1000, gamma=0.001;, score=0.004 total time= 2.0min
[CV 2/5] END ...............C=1000, gamma=0.001;, score=0.004 total time= 1.9min
[CV 3/5] END ...............C=1000, gamma=0.001;, score=0.004 total time= 2.9min
[CV 4/5] END ...............C=1000, gamma=0.001;, score=0.005 total time= 1.9min
[CV 5/5] END ...............C=1000, gamma=0.001;, score=0.005 total time= 1.9min
[CV 1/5] END ..............C=1000, gamma=0.0001;, score=0.004 total time= 1.9min
[CV 2/5] END ..............C=1000, gamma=0.0001;, score=0.004 total time= 1.9min
[CV 3/5] END ..............C=1000, gamma=0.0001;, score=0.004 total time= 2.9min
[CV 4/5] END ..............C=1000, gamma=0.0001;, score=0.005 total time= 1.9min
[CV 5/5] END ..............C=1000, gamma=0.0001;, score=0.005 total time= 1.8min

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
             verbose=3)

In [55]:
grid.best_params_

{'C': 0.1, 'gamma': 1}

In [56]:
grid_predictions = grid.predict(x_test)

C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- city_New Franken
- city_Pea Ridge
- city_Spirit Lake
- city_Springville
- city_West Bethel
- ...
Feature names seen at fit time, yet now missing:
- dob_28-10-1960
- trans_date_trans_time_01-01-2019 00:00
- trans_date_trans_time_01-01-2019 00:01
- trans_date_trans_time_01-01-2019 00:03
- trans_date_trans_time_01-01-2019 00:04
- ...

  warnings.warn(message, FutureWarning)

In [57]:
print(confusion_matrix(y_test,grid_predictions))
print("\n")
print(classification_report(y_test,grid_predictions))

[[14545     0]
 [   45     0]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14545
           1       0.00      0.00      0.00        45

    accuracy                           1.00     14590
   macro avg       0.50      0.50      0.50     14590
weighted avg       0.99      1.00      1.00     14590

C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Vivek\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))